In [1]:
%matplotlib inline

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

**A typical training procedure for a neural network is as follows:**

- Define the neural network that has some learnable parameters (or weights)
- Iterate over a dataset of inputs
- Process input through the network
- Compute the loss (how far is the output from being correct)
- Propagate gradients back into the network’s parameters
- Update the weights of the network, typically using a simple update rule: 
                                        weight = weight - learning_rate * gradient
- Define the network

In [3]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        
        # an affine operation: y = Wx + b
        
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 5*5 from image dimension 
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        
        # If the size is a square, you can specify with a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = torch.flatten(x, 1) # flatten all dimensions except the batch dimension
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


We just have to define the forward function, and the backward function (where gradients are computed) is automatically defined 
for us using autograd. We can use any of the Tensor operations in the forward function.

**The learnable parameters of a model are returned by net.parameters()**

In [4]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 5, 5])


Let's try a random 32x32 input. Note: expected input size of this net (LeNet) is 32x32. 
To use this net on the MNIST dataset, please resize the images from the dataset to 32x32.

In [5]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0654,  0.0396,  0.0624, -0.0983, -0.0488, -0.0166,  0.0146, -0.0645,
         -0.0450, -0.0440]], grad_fn=<AddmmBackward0>)


Zero the gradient buffers of all parameters and backprops with random gradients:

**Note
``torch.nn`` only supports mini-batches. 
The entire ``torch.nn`` package only supports inputs that are a mini-batch of samples, and not a single sample.**

**torch.Tensor** - A multi-dimensional array with support for autograd operations like backward(). Also holds the gradient w.r.t. the tensor.

**nn.Module** - Neural network module. Convenient way of encapsulating parameters, with helpers for moving them to GPU, exporting, loading, etc.

**nn.Parameter** - A kind of Tensor, that is automatically registered as a parameter when assigned as an attribute to a Module.

**autograd.Function** - Implements forward and backward definitions of an autograd operation. Every Tensor operation creates at least a single Function node that connects to functions that created a Tensor and encodes its history.

**LOSS FUNCTION**

A loss function takes the (output, target) pair of inputs, and computes a value that estimates how far away the output 
is from the target.

There are several different loss functions <https://pytorch.org/docs/nn.html#loss-functions>
under the nn package . A simple loss is: nn.MSELoss which computes the mean-squared error between the output and the target.

In [6]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()
print(output)
print(target)
loss = criterion(output, target)
print(loss)

tensor([[ 0.0654,  0.0396,  0.0624, -0.0983, -0.0488, -0.0166,  0.0146, -0.0645,
         -0.0450, -0.0440]], grad_fn=<AddmmBackward0>)
tensor([[ 0.2310, -0.9775, -0.4607, -0.3347, -1.2723, -0.5546, -1.9229,  1.0480,
         -1.1289,  0.2876]])
tensor(0.9454, grad_fn=<MseLossBackward0>)


Now, if you follow loss in the backward direction, using its .grad_fn attribute, 
you will see a graph of computations that looks like this:

**input -> conv2d -> relu -> maxpool2d -> conv2d -> relu -> maxpool2d
      -> flatten -> linear -> relu -> linear -> relu -> linear
      -> MSELoss
      -> loss**

So, when we call loss.backward(), the whole graph is differentiated w.r.t. the neural net parameters, 
and all Tensors in the graph that have requires_grad=True will have their .grad Tensor accumulated with the gradient.

In [7]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

**Backprop**
To backpropagate the error all we have to do is to loss.backward(). 
We need to clear the existing gradients though, else gradients will be accumulated to existing gradients.

Now we shall call loss.backward(), and have a look at conv1's bias gradients before and after the backward.

In [8]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([-0.0073, -0.0101,  0.0259,  0.0108, -0.0003, -0.0014])


**Update the weights**
The simplest update rule used in practice is the **Stochastic Gradient Descent (SGD):**

 ``weight = weight - learning_rate * gradient``

In [9]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

To use various different update rules such as SGD, Nesterov-SGD, Adam, RMSProp, etc. 
We use **torch.optim** that implements all these methods. 

In [10]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

In [11]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [12]:
print(output)

tensor([[ 0.0616,  0.0332,  0.0528, -0.1024, -0.0575, -0.0244, -0.0024, -0.0497,
         -0.0550, -0.0338]], grad_fn=<AddmmBackward0>)


In [13]:
print(loss)

tensor(0.9274, grad_fn=<MseLossBackward0>)
