In [1]:
%matplotlib inline

In [2]:
#To install PyTorch with Anaconda, you will need to open an Anaconda prompt via Start | Anaconda3 | Anaconda Prompt
#conda install -c pytorch pytorch

In [3]:
import numpy as np
import torch as tc

Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.

In [4]:
data = [[1, 2], [3, 4]]
x_data = tc.tensor(data)

In [5]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

Tensors can be created from NumPy arrays

In [6]:
np_array = np.array(data)
x_np = tc.from_numpy(np_array)

In [7]:
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


**From another tensor**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [8]:
x_ones = tc.ones_like(x_data) # retains the properties of x_data
#Returns a tensor filled with the scalar value 1
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = tc.rand_like(x_data, dtype=tc.float) # overrides the datatype of x_data
#Returns a tensor with the same size as input that is filled with random numbers
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0222, 0.0238],
        [0.5606, 0.1487]]) 



**With random or constant values:**

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [9]:
shape = (2, 3,)
rand_tensor = tc.rand(shape)
ones_tensor = tc.ones(shape)
zeros_tensor = tc.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6679, 0.8737, 0.7605],
        [0.8047, 0.3943, 0.1746]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Tensor Attributes**

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [10]:
tensor = tc.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**We move our tensor to the GPU if available**

In [11]:
if tc.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

**Standard numpy-like indexing and slicing**

In [12]:
tensor = tc.ones(4, 4)
print(tensor)
print("")
print("After indexing and slicing:")
print("")
tensor[:,1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

After indexing and slicing:

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension.**

In [13]:
t1 = tc.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Multiplying tensors**

In [14]:
# This computes the element-wise product
mul_tensor = tensor * tensor
print(f"tensor * tensor \n {mul_tensor}")

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.**

In [15]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**Note:**
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. 
Hence, their use is discouraged.

**Bridge with NumPy**

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change    the other.

In [16]:
t = tc.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [17]:
t.add_(1)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**NumPy array to Tensor**

In [18]:
n2 = np.ones(5)
t2 = tc.from_numpy(n2)

In [19]:
print(n2)
print("")
print(t2)

[1. 1. 1. 1. 1.]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


**Changes in the NumPy array reflects in the tensor.**

In [20]:
np.add(n2, 1, out=n2)

print(f"t: {t2}")
print(f"n: {n2}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
